= Fulcro RAD Semantic UI Rendering Plugin

A rendering plugin for Fulcro RAD that can render forms, reports, and containers for web UI. It leverages
https://fomantic-ui.com/introduction/getting-started.html[Semantic UI (Fomatic) CSS], which is easy to theme,
and has support for advanced (and controllable) React-based controls via https://react.semantic-ui.com/[Semantic UI React].

RAD UI plugins are meant to be an easy-to-escape first draft of UI. Most applications have a lot of back-end support
interfaces where the UI does not have to be pixel perfect, it just has to work. As such, a RAD UI plugin can save you
a lot of boilerplate and effort for screens that have little need for marketing appeal.

NOTE: Do not expect these renderings to be ideal in all cases. Some controls may not align perfectly and such.
Please feel free to submit PRs if you see a way to clean up a particular layout that is less than optimal.

== Usage

image:https://img.shields.io/clojars/v/com.fulcrologic/fulcro-rad-semantic-ui.svg[link=https://clojars.org/com.fulcrologic/fulcro-rad-semantic-ui]

To use this library simply install the controls on your RAD application:

[source]
-----
(ns com.example.main
  (:require
    [com.fulcrologic.rad.application :as rad-app]))

(defonce app (-> (rad-app/fulcro-rad-app)
                 (rad-app/install-ui-controls! sui/all-controls)))
-----

See the `fulcro-rad-demo` for a complete demo of most of the features of this library. Many of the
features are covered in https://github.com/fulcrologic/fulcro-rad-demo[that demo] and
in the http://book.fulcrologic.com/RAD.html[book].

== LICENSE

The MIT License (MIT)
Copyright (c), Fulcrologic, LLC

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

